conn movitel-emola
    type=tunnel
    authby=secret
    ikev2=insist

    # --- Teu lado (EC2) ---
    left=%defaultroute
    leftid=15.240.80.231
    leftsubnet=172.31.12.132/32

    # --- Movitel ---
    right=197.218.1.250
    rightid=197.218.1.250
    rightsubnet=10.229.16.29/32,10.229.16.30/32,10.229.42.197/32,10.229.41.48/32,10.229.41.49/32

    # --- Phase 1 ---
    ike=aes256-sha2_256-modp2048
    ikelifetime=86400s

    # --- Phase 2 ---
    esp=aes256-sha2_256
    salifetime=3600s
    pfs=no

    auto=start
    dpdaction=restart
    dpddelay=30
    dpdtimeout=120