export enum OrderStatus {
  INITIATED = "INITIATED",
  CREATED = "CREATED",
  PREPARING = "PREPARING",
  READY = "READY",
  DRIVER_ACCEPTED = "DRIVER_ACCEPTED",
  DISPATCHED = "DISPATCHED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  NEARBY = "NEARBY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}

// REJECTED = "REJECTED",
