export enum OrderStatus {
  INITIATED = "INITIATED", // OrderEventType = ORDER_INITIATED
  CREATED = "CREATED", // OrderEventType = ORDER_CREATED
  PREPARING = "PREPARING", // OrderEventType = ORDER_PREPARING_STARTED
  PICKING_UP = "PICKING_UP", // OrderEventType = ORDER_PICKUP_STARTED
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY", // OrderEventType = ORDER_OUT_FOR_DELIVERY
  NEARBY = "NEARBY", // OrderEventType = ORDER_NEARBY
  DELIVERED = "DELIVERED", // OrderEventType = ORDER_DELIVERED
  //
  PAID = "PAID",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  FULFILLED = "FULFILLED",
}
